version: '3.9'

services:
  database_quizzing:
    image: postgres
    container_name: database_quizzing
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=quizzing
      - POSTGRES_PASSWORD=boilerplate
      - POSTGRES_DB=api-quizzing
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
